### ISSUE TITLE
something wrong when I run "python server.py A"

### ISSUE THREAD

**Issue by qidaneix** [cocagne/multi-paxos-example#1]
Hi Tom:

How is everything going?

I listened your suggestion and read your code
[https://github.com/cocagne/multi-paxos-example](url)

but something wrong when I try to run "python server.py A"
It said

```
Traceback (most recent call last):
  File "server.py", line 45, in <module>
    m = Messenger(args.uid, config.peers, r)
  File "C:\Users\xiaoj\Documents\multi-paxos-example\messenger.py", line 19, in __init__
    for k,v in self.addrs.items():
RuntimeError: dictionary changed size during iteration
```

and the line 19 of messenger.py is here:

```
        # provide two-way mapping between endpoints and server names
        for k,v in self.addrs.items():
            self.addrs[v] = k
```

I don't understand what's the meaning of those two line, you could help me about that? Thank you!

best wishes!

Jin

**Comment by cocagne** [comment]
That's a bug. I've just pushed the fix which is to wrap the
"self.addrs.items()" with a call to "list()". Let me know if that doesn't
solve the problem. Also, this code is written for Python 2.7. If you're
trying to run it with Python 3, it almost certainly will not work.

Cheers,

Tom
