### ISSUE TITLE
something wrong when I try to propose a value from client

### ISSUE THREAD

**Issue by qidaneix** [cocagne/multi-paxos-example#2]
Tom,

Hi!

I have configed multi-paxos-example in my computer windows7 64bit.
```
# (IP,UDP Port Number)
peers = dict( A=('127.0.0.1',1234),
              B=('127.0.0.1',1235),
              C=('127.0.0.1',1236) )

# State files for crash recovery. Windows users will need to modify
# these.
state_files = dict( A='E:\\multi-paxos-example\\tmp\\A.json',
                    B='E:\\multi-paxos-example\\tmp\\B.json',
                    C='E:\\multi-paxos-example\\tmp\\C.json' )
```
And try to run it. But when I run a client
`python client.py B eee`
It comes up a Error.
```
Error processing packet:  accept {"instance_number": 0, "proposal_id": [1, "B"],
 "proposal_value": "eee"}
Traceback (most recent call last):
  File "E:\multi-paxos-example\messenger.py", line 55, in datagramReceived
    handler(from_uid, **kwargs)
  File "E:\multi-paxos-example\resolution_strategy.py", line 82, in receive_acce
pt
    super(ExponentialBackoffResolutionStrategyMixin,self).receive_accept(from_ui
d, instance_number, proposal_id, proposal_value)
  File "E:\multi-paxos-example\replicated_value.py", line 176, in receive_accept

    proposal_id, proposal_value)
  File "E:\multi-paxos-example\replicated_value.py", line 72, in save_state
    os.rename(tmp, self.state_file)
WindowsError: [Error 183]
```
I google it and it means file existed, but I don't know how to solve it. Can you  help me about that?
Thanks!

Jin

**Comment by qidaneix** [comment]
Whats more, I try it on linux, ubuntu. It doesn't come out Error any more, and a.json/b.json/c.json has a log
`{"current_value": "test111", "instance_number": 5, "promised_id": null, "accepted_id": null, "accepted_value": null}`

**Comment by cocagne** [comment]
Interesting. Apparently it's an error on windows to rename a file to one
that already exists. On Posix file systems this is a standard mechanism for
doing atomic file updates as the filesystem itself explicitly supports this
operation and guarantees that the rename will occur atomically. The quick
fix on windows would be to just delete the file before the rename operation
if it already exists. That opens up a window during which a crash could
lose data but it's just a toy application anyway ;-)
